# Base image with Amazon Corretto JDK 21
FROM amazoncorretto:21

# Set working directory
WORKDIR /app

# Copy JAR file to the container
COPY build/libs/server-0.0.1-SNAPSHOT.jar /app/server.jar

# Set environment variables for timezone and Spring profile
ENV TZ=Asia/Seoul
ENV SPRING_PROFILES_ACTIVE=staging

# Expose default Spring Boot port
EXPOSE 8080

# Run the application
CMD ["java", "-Duser.timezone=$TZ", "-jar", "-Dspring.profiles.active=$SPRING_PROFILES_ACTIVE", "server.jar"]